---
- name: Create RDS database instance
  hosts: all
  connection: local
  collections:
    - amazon.aws

  vars:
    aws_region: "us-east-1"
    db_engine: "mysql"
    db_identifier: "my-rds"
    db_instance_class: "db.t4g.micro"
    db_allocated_storage: 20
    db_master_username: "admin"
    db_master_password: "Newpasword123"

  tasks:
    - name: Create RDS instance
      amazon.aws.rds_instance:
        state: present
        region: "{{ aws_region }}"
        engine: "{{ db_engine }}"
        db_instance_identifier: "{{ db_identifier }}"
        db_instance_class: "{{ db_instance_class }}"
        allocated_storage: "{{ db_allocated_storage }}"
        master_username: "{{ db_master_username }}"
        master_user_password: "{{ db_master_password }}"

    - name: Wait for RDS instance to become available
      wait_for:
        host: "{{ lookup('amazon.aws.rds', db_identifier).endpoint }}"
        port: 3306
        state: started
        timeout: 300
